### ISSUE TITLE
Back End - Set up API enpdoints for saving emails

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/Internado#100]
This involves creating a DB table, and an endpoint that takes an email address and puts it in the database. Maybe should have validation for duplicates and whether it  is a valid email address.

**Comment by kimoantiqe** [comment]
I am handiling all of that in  #30 , you can check feature/30 : controllers/UserController.js for more details.. 
I am currently finallizing some stuff and will create a PR soon
