### ISSUE TITLE
Create rough frontend

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/Internado#12]
We should create a basic frontend application that has the initial features for our MVP. This would probably consist of a form with a search bar and selection for different options such as type of internship, location, etc. I believe we discussed that this should be written in React.

**Comment by AmirNaghibi** [comment]
I strongly agree!! We also need some sort of wireframe that shows how the application looks like

**Comment by DConnorFong** [comment]
Blocked until wireframe is provided
