### ISSUE TITLE
Talk to strategy about Digital Ocean sponsorship

### ISSUE THREAD

**Issue by cowmanjoe** [ubclaunchpad/Internado#176]

**Comment by AmirNaghibi** [comment]
<img width="476" alt="screen shot 2019-02-08 at 11 57 23 am" src="https://user-images.githubusercontent.com/20001191/52502878-bbf61200-2b98-11e9-840b-ca46f9e39793.png">

Some great resources recommended by Robert. We have mainly using Azure for hosting. I can look into AWS if needed for deploying our app
