### ISSUE TITLE
ElasticSearch Research

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/Internado#29]
1. How expensive is ElasticSearch (run some tests)?
2. Ask Bruno what our available resources are. 
3. Are there alternate ways to implement the same functionality?
4. Should we be using ElasticSearch?

**Comment by cormacjmollitor** [comment]
Are we considering any other search engines like Solr? If so, the link below is a pretty good article comparing the two.
https://logz.io/blog/solr-vs-elasticsearch/

**Comment by bobheadxi** [comment]
I’ve worked with both Elasticsearch and Solr - shoot me a message on slack if you want to chat about this!
