### ISSUE TITLE
Start Folder Repository Structure

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/Internado#33]
Requirements:
* Add front_end folder to repository root
* Add back_end folder to repository root
* Add data_acquisition folder to repository root

Notes:
* Merge directly back into the develop branch so tasks starting this week can populate the folders

**Comment by DConnorFong** [comment]
Assigning to blocked - the first frond end, back end, and data acquisition (python?) cases should cover these as you can't add empty folders easily.

**Comment by AmirNaghibi** [comment]
we could maybe add some dummy files like data_acquisition.py to the folders. We can change the names later.

**Comment by DConnorFong** [comment]
@AmirNaghibi I think I might do that - I'll also look into maybe a React boilerplate to put in.

**Comment by DConnorFong** [comment]
Testing on feature/32
