### ISSUE TITLE
Sprint 1 - Front End - UX/UI Mockup 

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/Internado#50]

**Comment by AmirNaghibi** [comment]
Is there anything blocking this task?

**Comment by stephqwu** [comment]
I think I need to add and get feedback on some more views on https://app.zenhub.com/workspace/o/ubclaunchpad/internado/issues/6 before I can create the experience at this level of detail.

Also I will need feedback on branding decisions https://app.zenhub.com/workspace/o/ubclaunchpad/internado/issues/62

Maybe those should be added as dependencies? But I'm not sure

**Comment by frostyshadows** [comment]
From the ZipRecruiter documentation:
<img width="1334" alt="screen shot 2018-11-22 at 3 23 52 pm" src="https://user-images.githubusercontent.com/12488887/48924231-b6770e80-ee6a-11e8-93c7-2e9c74463c31.png">

Here's the HTML for the USA logo: `<a href="https://www.ziprecruiter.com/jobs" id="jobs_widget_link"><span>Job Search by</span> <span id="zr_logo_container"><img id="zr_logo" src="https://www.ziprecruiter.com/img/logos/logo-sm-black-304px.png" alt="ZipRecruiter" width="120" /></span></a>`

**Comment by DConnorFong** [comment]
Further design tickets should be addressed more specifically.
