### ISSUE TITLE
Project wireframe and user experience

### ISSUE THREAD

**Issue by AmirNaghibi** [ubclaunchpad/Internado#6]

**Comment by cormacjmollitor** [comment]
Wireframe for recommended job postings
https://wireframe.cc/ayAKyS

Wireframe for job postings with user-inputted filters
https://wireframe.cc/LxHnGp

**Comment by stephqwu** [comment]
(Work in progress)
https://www.fluidui.com/editor/live/preview/cF9Oazdja0hzQ1BXc0kwMVVaeFpMQ000Q2JKVEtlREZTTg==

Please leave comments to notify me about what you think works and doesn't work before I can move on to https://github.com/ubclaunchpad/Internado/issues/50

**Comment by DConnorFong** [comment]
@stephqwu the tornado icon is looking pretty good. Maybe just another dropdown to do some sort of location filtering (vancouver, seattle etc)?

**Comment by AmirNaghibi** [comment]
It would be great if we could consider other logo options (specially a bit colorful??), I like these:

<img width="237" alt="screen shot 2018-10-25 at 12 58 26 am" src="https://user-images.githubusercontent.com/20001191/47484784-6ec08100-d7f1-11e8-8809-a16aaf7ddf7e.png">
<img width="230" alt="screen shot 2018-10-25 at 12 59 35 am" src="https://user-images.githubusercontent.com/20001191/47484785-6ec08100-d7f1-11e8-988b-f6079b3b14da.png">
<img width="184" alt="screen shot 2018-10-25 at 12 59 29 am" src="https://user-images.githubusercontent.com/20001191/47484786-6ec08100-d7f1-11e8-99ae-f400e9ad3b7c.png">
