### ISSUE TITLE
Sprint 1 - Set up website

### ISSUE THREAD

**Issue by frostyshadows** [ubclaunchpad/Internado#67]
- [x] deploy a frontend server on azure
- [x] set up website on it
- [ ] get a domain name  e.x internado.com or internado.ca (no need for custom domain for now)

**Comment by AmirNaghibi** [comment]
Resources for Free Domain to check:
- Doamin.com

**Comment by AmirNaghibi** [comment]
Get a domain name?

Update front end React component.
