### ISSUE TITLE
Sprint 1 - Internado Landing Page

### ISSUE THREAD

**Issue by AmirNaghibi** [ubclaunchpad/Internado#70]
You can check the current Homepage UI in 
1. check out integration/1.0 branch
2. go to the client folder
3. npm install
4. npm run build
5. npm start

please keep the current header
- [x]  add landing page with Internado Logo
- [x]  enable users to add their email to be notified when Internado is launched
- [ ]  link to privacy policy [someone please give me the link]

**Comment by stephqwu** [comment]
Where do the emails go?

**Comment by stephqwu** [comment]
Would they get stored somewhere?

**Comment by AmirNaghibi** [comment]
Yeah I have to set up a location to store the emails. Just have the email field and I will connect it to the backend database for db
