### ISSUE TITLE
Sprint 1 - Front End - React/Redux Refactor

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/Internado#77]

**Comment by DConnorFong** [comment]
@cormacjmollitor can we get a status update on this?

**Comment by cormacjmollitor** [comment]
Currently still working on it. I'm gonna have to majorly refactor a majority of the frontend files to follow the recommended data flow scheme for Redux. I can push what I currently have now tho if you want.

**Comment by frostyshadows** [comment]
Sounds good, is everything off the latest develop? We just merged a lot of changes from integration/1.0 into develop

**Comment by cormacjmollitor** [comment]
Not yet. I'll rebase and cry over merge conflicts soon though.

**Comment by DConnorFong** [comment]
No longer using Redux
