### ISSUE TITLE
Sprint 2 - Front End - API Calls to Server

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/Internado#98]

**Comment by frostyshadows** [comment]
@cowmanjoe @DConnorFong looks like the code for calling the search API is already in the Navbar.js file? I still don't have access to the Postgres DB so can't really test it.

**Comment by cowmanjoe** [comment]
It looks like you’re right. We need to prioritize #59 so we can ease testing because I think this is slowing us down substantially.

**Comment by cowmanjoe** [comment]
I’m not sure if we should close this yet as i don’t think it’s been tested, but it has been merged in to develop.
